### PR TITLE
#94 Add details of how to apply for an Agency

### PR DESCRIPTION
**Pull request by john-shepherdson**
Added new page and related form
Plus general cleanup
Updated CHANGELOG

### CODE REVIEW

**Comment by schildwaechter** [comment]
I'm a bit confused to see this in the technical documentation of the CESSDA infrastructure.
This is, after all, something that the user of the CVS needs to do and not some technical detail in the background of the infrastructure operation.
So I would expect this as part of the CVS user documentation.

**Comment by matthew-morris-cessda** [comment]
This should be added to the CVS documentation. not the general technical documentation.

**Comment by matthew-morris-cessda** [comment]
The non-CVS documentation should be moved to a separate PR.

**Comment by john-shepherdson** [comment]
I disagree. The User Guide is for consumers of the published CVs. There is no reason to believe they have any interest in creating and managing their own CVs, so why would they care about setting up an Agency? It is a bit like adding a section in a car owners guide that explains how to set up a car dealership. 

There is a case for saying that this information should be part of the Content Editors guide, but you cannot access that unless you have a CVS account, in which case you are part of an Agency already.

**Review by matthew-morris-cessda — APPROVED** [review]

**Pull request merged**
